"""perubahan nama kolom pada tabel story

Revision ID: c91f088e2ba8
Revises: 82438e476afe
Create Date: 2023-11-26 09:02:52.734313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c91f088e2ba8'
down_revision: Union[str, None] = '82438e476afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('short_story', sa.String(), nullable=False))
    op.drop_column('story', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('story', 'short_story')
    # ### end Alembic commands ###
